AWSTemplateFormatVersion: '2010-09-09'
Description: |
  CloudFormation template for a custom IAM Managed Policy.
  This policy grants permissions to create/list S3 buckets and manage objects within them.

Parameters:
  PolicyName:
    Type: String
    Description: The name for the IAM managed policy.
    Default: 'S3-Bucket-And-Object-Management-Policy'

Resources:
  S3ManagementPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: !Ref PolicyName
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 's3:ListAllMyBuckets'
              - 's3:GetBucketLocation'
            Resource: '*'
          - Effect: Allow
            Action:
              - 's3:CreateBucket'
              - 's3:ListBucket'
              - 's3:PutObject'
              - 's3:GetObject'
              - 's3:DeleteObject'
            Resource: 'arn:aws:s3:::*'
      Description: 'Policy for creating/listing S3 buckets and managing objects.'

Outputs:
  PolicyArn:
    Description: The ARN of the created IAM managed policy.
    Value: !Ref S3ManagementPolicy
    Export:
      Name: !Sub '${AWS::StackName}-PolicyArn'
